name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: yinnam91/cicd-test-app   # Format: <dockerhub_account>/<repo>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        
      - name: Build and tag Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Publish Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest